### ISSUE TITLE
Windows issues - Logitech Unify Version 

### ISSUE THREAD

**Issue by lgbeno** [BastilleResearch/nrf-research-firmware#13]
I was able to flash the dongle and use it in in Ubuntu however in Windows 10 when inserting the device, Windows first identifies it as "Unknown" in device manager and then it plays the disconnect sound multiple times.  Using pyusb or hidapi, I cannot seem to find it either.

**Comment by lgbeno** [comment]
Closing issue, this is my error.

**Comment by TechInterMezzo** [comment]
@lgbeno Looks like I am having te same problem. How did you solve it?
