### ISSUE TITLE
Bluetooth support for unifying dongle?

### ISSUE THREAD

**Issue by lesleyxyz** [BastilleResearch/nrf-research-firmware#30]
Hi,

I like the fact that this repo managed to have support for flashing a Logitech Unifying adapter.
I was wondering if I could somehow use the code to flash something on the unifying dongle so it acts like a regular BLE device which I can use in Windows/Linux to control other devices.

IIRC, the nRF24LU1+ seems to be able to do this with it's standard firmware.

Thank you

**Comment by zerog2k** [comment]
TLDR, not possible.

BLE (Bluetooth 4.0) and Nordic's ShockBurst (SB) & Enhanced ShockBurst (ESB) protocols are unrelated, other than they are both on 2.4GHz ISM band.
Some Nordic devices like nRF51 and nRF52 can handle either stack (bluetooth or ESB), but the nRF24LU1+ and related nRF24 family (nRF24L01+, nRF24LE1) only do the proprietary Nordic SB/ESB protocols.

**Comment by lesleyxyz** [comment]
Okay thank you for your interesting reply!
